- src/client/clouds.cpp
Speed up cloud rendering (especially 3D clouds on slow devices)
1. Optimize cloud mesh: the faces that were culled aren’t even generated now
2. Optimize mesh generation: (see the code)
This PR is Ready for Review.
Walk around; fly around clouds, above and below (esp. above +200 and below 0). The clouds should look as usual but render faster.
> Optimize clouds

- builtin/game/item.lua
> Make core.item_drop work properly with pipeworks

- build/android/app/src/main/java/com/multicraft/game/helpers/Utilities.kt
- build/android/build.gradle
- src/debug.cpp
- src/porting_android.cpp
- src/porting_android.h
- Somehow debug.cpp does not re-throw errors to the main thread anymoree so I have to handle them right in the method 
This PR is a Ready for Review.
> Handle errors in debug.cpp

- builtin/mainmenu/dlg_create_world.lua
- builtin/mainmenu/dlg_create_world_default.lua
This "mapgen" is just the flat mapgen with the caves, dungeons, and decorations flags disabled.
> Add superflat "mapgen"

- src/server/player_sao.cpp
> Fix drowning in MTG doors

- src/script/cpp_api/s_base.cpp
There's probably a nicer way to do this.
> Load string.buffer (if it exists)

- src/script/cpp_api/s_base.cpp
> Add string.buffer (again)

- src/mapgen/mapgen_v7p.cpp
These variables were uninitialised which would lead to unpredictable behaviour and dungeons being really hard to find (I never managed to find one).
> Initialise some variables in v7p

- src/client/renderingengine.cpp
Usage: cmake .. -DUSE_SDL=1 -DIRRLICHT_SOURCE_DIR=/path/to/irrlicht
> Add a possibility to run SDL version on linux.

- src/gui/guiButton.cpp
- src/gui/guiFormSpecMenu.cpp
- src/gui/guiScrollContainer.cpp
- src/gui/guiScrollContainer.h
- src/gui/guiTable.cpp
- src/gui/guiTable.h
Needs https://github.com/MoNTE48/Irrlicht/pull/15
> Add swipe gesture for guitable and scroll container

- Android/app/build.gradle
- Android/app/src/main/AndroidManifest.xml
- Android/app/src/main/java/com/multicraft/game/helpers/ApiLevelHelper.kt
- Android/app/src/main/java/com/multicraft/game/workmanager/UnzipWorker.kt
- Android/app/src/main/java/org/libsdl/app/HIDDeviceManager.java
- Android/app/src/main/java/org/libsdl/app/SDLActivity.java
- Android/build.gradle
- Android/gradle.properties
- Android/gradle/wrapper/gradle-wrapper.properties
- Android/native/build.gradle
- src/porting_android.cpp
- Fix unzip on Android 14
- Bump dependencies versions
- Other minor fixes
This PR is a Ready for Review.
> Android 14 changes

- builtin/fstk/buttonbar.lua
- builtin/mainmenu/common.lua
- builtin/mainmenu/serverlistmgr.lua
- builtin/mainmenu/tab_local.lua
- builtin/mainmenu/tab_online.lua
> Revert tab code

- doc/lua_api.txt
- src/gui/guiEditBoxWithScrollbar.cpp
- src/gui/guiEditBoxWithScrollbar.h
- src/gui/guiFormSpecMenu.cpp
- src/gui/guiHyperText.cpp
- src/gui/guiHyperText.h
- src/gui/guiScrollBar.cpp
- src/gui/guiScrollBar.h
- src/gui/guiTable.cpp
- src/gui/guiTable.h
Only pressing the buttons makes a sound, using the up/down keyboard buttons or scroll wheel doesn't make any sound.
> Add scrollbar button sounds

- src/client/hud.cpp
> Fix HUD image size when specified relative to screen size

- src/gui/guiKeyChangeMenu.cpp
- src/gui/guiKeyChangeMenu.h
Currently the button is just in the bottom right corner
> Add reset button to key change menu

- src/client/joystick_controller.cpp
Boat wants left/right/up/down keys rather than gamepad axes state.
> Fixed boat movement when playing with gamepad.

- builtin/settingtypes.txt
- multicraft.conf.example
- src/client/clientlauncher.cpp
- src/client/game.cpp
- src/defaultsettings.cpp
- src/gameparams.h
> Add "connect_timeout" setting

- builtin/settingtypes.txt
- multicraft.conf.example
- src/defaultsettings.cpp
- src/map.cpp
- src/server.cpp
> Fix zstd compression levels, sen min net compression level in singleplayer

- src/client/game.cpp
- src/client/tile.cpp
- src/client/tile.h
- src/gui/guiEngine.cpp
- src/gui/guiEngine.h
I suspect I'm missing something with the texture code, it feels weird that I have removed more code than I have added.
> Allow using texture modifiers from the main menu

- builtin/client/sscsm.lua
> Add core.sound_fade to SSCSM API

- src/gui/guiFormSpecMenu.cpp
- src/gui/guiScrollContainer.cpp
- src/gui/guiScrollContainer.h
Tested by replacing `#ifdef HAVE_TOUCHSCREENGUI` with `#if 1` in relevant places
> Allow swiping to drag horizontal scroll containers

- doc/lua_api.txt
- src/client/client.cpp
- src/clientiface.cpp
- src/clientiface.h
- src/network/serverpackethandler.cpp
- src/script/lua_api/l_server.cpp
- src/server.cpp
- src/server.h
> Include client's RAM in get_player_information
